language: ruby
before_install:
  - gem install bundler
matrix:
  include:
    - rvm: 2.1.10
      gemfile: Gemfile
    - rvm: 2.2.8
      gemfile: Gemfile
    - rvm: 2.3.5
      gemfile: Gemfile
    - rvm: 2.4.2
      gemfile: Gemfile
    - rvm: 2.4.1
      gemfile: Gemfile
